function Atotal = vtkarea(filename)
% Compute the area of a subcortical region
% from a VTK file generated by FSL-FIRST.
%
% Usage:
% area = vtkarea(filename)
%
% _____________________________________
% Anderson M. Winkler
% Yale University / Institute of Living
% Nov/2009

[Vtx,Fac] = vtkread(filename);

A = zeros(size(Fac,1));
for f = 1:size(Fac,1),
    M = zeros(3);
    for v = 1:3,
        M(:,v) = Vtx(Fac(f,v),:)';
    end
    A(f) = calc_tri(M);
end
Atotal = sum(A(:));


function Area = calc_tri(M)
Mxy = M;  Mxy(3,:) = [1 1 1];
Myz = M;  Myz(1,:) = [1 1 1];
Mxz = M;  Mxz(2,:) = [1 1 1];
Area = .5 * sqrt(det(Mxy)^2 + det(Myz)^2 + det(Mxz)^2);